title: "咖啡香"
author: "Klaus Ma"
description: "Klaus's own thoughts on Distributed Computing"
permalink: pretty
lang: "en"

show_footer: false           # show the "previous" and "next" links at the end of each post
dark_theme: false            # use the dark mode as default
dark_header: true            # keep the header dark
dark_footer: false           # keep the footer dark
# style: minimal             # use a simpler style inspired by the minima theme

navigation:                  # site navigation in the header
  - about.md
  - Github: "http://github.com/k82cn"

#icons:                      # icons in the header, see http://fontawesome.com/icons
#  envelope: "mailto:niklasbuschmann@users.noreply.github.com"
#  github: "https://github.com/niklasbuschmann/contrast"
#  rss: "/contrast/feed.xml"

comments:                    # embed disqus or isso comments
  disqus: "k82cn"
#  isso: ""

plugins:
 - jekyll-feed
 - jekyll-default-layout
