# standard jekyll configuration options

exclude: ['Rakefile', 'README.md', 'config.rb']

# configuration required for some pages

domain: cguru.net
title: CGURU.NET
author: Klaus Ma
email: klaus@cguru.net

permalink:    pretty 

